"""Generators that turn a detected framework into a Dockerfile.

Every generator here obeys three rules.

**Secrets are mounted, never baked.** A build that needs `DATABASE_URL` or
`NEXT_PUBLIC_API_URL` gets them through a BuildKit secret mount, which exists
for the life of one RUN instruction and is not written to any layer. Passing
them as ARG would put every one of them in `docker history`, readable by
anyone who can reach the image.

**The runtime stage carries no toolchain.** The image that serves traffic has
no compiler, no package manager cache and, wherever the language allows, no
shell. This is most of the difference between a 90 MB image and a 1.2 GB one,
and all of the difference in how much of the host an escaped process can see.

**Nothing runs as root.** Each runtime stage drops to an unprivileged user
before CMD.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from deploypro.domain.buildplan import (
    DEFAULT_PORT,
    GO_IMAGE,
    NODE_IMAGE,
    PYTHON_IMAGE,
    STATIC_IMAGE,
    BuildPlan,
)

#: Where the engine writes the build-time environment file. Referenced by the
#: secret mount in every generated build stage.
ENV_SECRET_ID = "env"
ENV_SECRET_PATH = "/run/secrets/env"


def cache_mount(target: str, name: str) -> str:
    """A BuildKit cache that survives between builds and is in no layer.

    Package managers re-download everything when the dependency layer is
    rebuilt — which is every time a lockfile changes. A cache mount keeps the
    downloads on the host instead, so a one-line dependency bump fetches one
    package rather than all of them, and the image is no larger for it.

    Shared by every project on the host, keyed by tool. That is the same trust
    boundary the platform already has: one owner, one token, and every
    project's build runs on the same daemon. Caches are content-addressed by
    the tools that use them, and lockfile integrity hashes still apply.
    `sharing=locked` because two package managers writing one cache at once is
    how caches get corrupted.
    """
    return f"--mount=type=cache,id=deploypro-{name},target={target},sharing=locked"


@dataclass(frozen=True, slots=True)
class NodeToolchain:
    """Which package manager the repository is asking for.

    Decided by lockfile, never by preference. Running `npm ci` on a tree with a
    `pnpm-lock.yaml` resolves a different dependency graph than the author
    tested, which is the kind of difference that only shows up in production.
    """

    name: str
    lockfile: str | None
    install: str
    setup: tuple[str, ...] = ()
    #: Where this tool keeps its download cache when running as root.
    cache_dir: str = "/root/.npm"

    @property
    def cache(self) -> str:
        return cache_mount(self.cache_dir, self.name)

    @property
    def run_prefix(self) -> str:
        return "npm run" if self.name == "npm" else f"{self.name} run"


NPM = NodeToolchain("npm", "package-lock.json", "npm ci --no-audit --no-fund")
NPM_NO_LOCK = NodeToolchain("npm", None, "npm install --no-audit --no-fund")
PNPM = NodeToolchain(
    "pnpm",
    "pnpm-lock.yaml",
    "pnpm install --frozen-lockfile",
    setup=("corepack enable pnpm",),
    cache_dir="/root/.local/share/pnpm/store",
)
YARN = NodeToolchain(
    "yarn",
    "yarn.lock",
    "yarn install --frozen-lockfile",
    setup=("corepack enable yarn",),
    cache_dir="/usr/local/share/.cache/yarn",
)
BUN = NodeToolchain(
    "bun",
    "bun.lockb",
    "bun install --frozen-lockfile",
    setup=("npm install -g bun@1",),
    cache_dir="/root/.bun/install/cache",
)


def build_env_mount(command: str, *, mounts: tuple[str, ...] = ()) -> str:
    """Wrap a build command so the project's variables are set while it runs.

    The file may legitimately be absent — a project with no variables at all —
    so its absence is not an error. `set -a` exports everything the file
    defines without each line needing its own `export`.
    """
    extra = "".join(f"{mount} \\\n    " for mount in mounts)
    return (
        f"RUN {extra}--mount=type=secret,id={ENV_SECRET_ID} \\\n"
        f"    set -a; [ -f {ENV_SECRET_PATH} ] && . {ENV_SECRET_PATH}; set +a; \\\n"
        f"    {command}"
    )


def _header(framework: str) -> list[str]:
    return [
        "# syntax=docker/dockerfile:1.7",
        "#",
        f"# Generated by DeployPro for a {framework} project.",
        "# Not committed to the repository: it is regenerated on every deploy,",
        "# so a fix to the platform reaches this project without a commit here.",
        "",
    ]


def _install_stage(tc: NodeToolchain, *, stage: str = "deps") -> list[str]:
    """Dependencies in their own stage, keyed on the manifest alone.

    Copying only the manifest and lockfile means the install layer is reused
    for every build that did not change dependencies, which is nearly all of
    them. Copying the whole tree first — the obvious way to write it — would
    invalidate that layer on every commit.
    """
    lines = [f"FROM {NODE_IMAGE} AS {stage}", "WORKDIR /app"]
    lines += [f"RUN {cmd}" for cmd in tc.setup]
    manifests = "package.json"
    if tc.lockfile:
        manifests += f" {tc.lockfile}"
    lines += [
        f"COPY {manifests} ./",
        f"RUN {tc.cache} {tc.install}",
        "",
    ]
    return lines


def _static_runtime(
    *,
    source_stage: str,
    output_dir: str,
    spa: bool,
    port: int,
) -> tuple[list[str], tuple[tuple[str, str], ...]]:
    """Serve a directory of files with Caddy.

    `spa` decides what happens to a path that matches no file. A single-page
    app must answer `/settings` with `index.html` and let the router sort it
    out; a statically exported site must answer 404, because serving the home
    page under every wrong URL is how a site gets its 404s indexed as
    duplicates of its front page.

    The response headers are the platform's, not the project's, because a
    static site has nowhere else to put them: there is no server to run a
    middleware in, and Next's `headers()` is unsupported under
    `output: 'export'`. A project moving here from a host that set them in
    its own configuration file would otherwise lose them silently, which is
    the worst way to lose a security header. `X-Frame-Options: DENY` is the
    one opinionated choice — a site meant to be embedded in an iframe needs
    it lifted, and today that means not using the generated Dockerfile.
    """
    fallback = (
        "try_files {path} {path}/ {path}.html /index.html"
        if spa
        else "try_files {path} {path}.html {path}/index.html"
    )
    # A site that renders its own 404 page should serve it. Caddy answers a
    # missing file with a bare status line otherwise, which for an exported
    # Next site means the 404.html it just built is never seen. An SPA never
    # reaches here: its fallback matches everything.
    not_found = (
        []
        if spa
        else [
            "",
            "\thandle_errors {",
            "\t\t@404 expression {err.status_code} == 404",
            "\t\trewrite @404 /404.html",
            "\t\tfile_server",
            "\t}",
        ]
    )
    caddyfile = "\n".join(
        [
            "{",
            "\tauto_https off",
            "\tadmin off",
            "}",
            "",
            f":{port} {{",
            "\troot * /srv",
            "\tencode zstd gzip",
            f"\t{fallback}",
            "\tfile_server",
            "",
            "\t# Baseline headers for every static site on the platform. See the",
            "\t# docstring for why they live here and not in the project.",
            "\theader {",
            "\t\tX-Content-Type-Options nosniff",
            "\t\tReferrer-Policy strict-origin-when-cross-origin",
            "\t\tX-Frame-Options DENY",
            "\t\t# Naming the server and its version only helps whoever is",
            "\t\t# looking for hosts running a version with a known bug.",
            "\t\t-Server",
            "\t}",
            "",
            "\t# Immutable build output is safe to cache hard; HTML is not,",
            "\t# because the next deploy must be visible on the next request.",
            "\t@immutable path /_next/static/* /assets/* /static/*",
            '\theader @immutable Cache-Control "public, max-age=31536000, immutable"',
            "\t@html path *.html /",
            '\theader @html Cache-Control "public, max-age=0, must-revalidate"',
            *not_found,
            "}",
            "",
        ]
    )
    lines = [
        f"FROM {STATIC_IMAGE} AS run",
        "COPY Caddyfile /etc/caddy/Caddyfile",
        f"COPY --from={source_stage} /app/{output_dir} /srv",
        "# The image ships caddy with the cap_net_bind_service file capability",
        "# so an unprivileged user can bind :80. Every container here runs with",
        "# no-new-privileges, and the kernel refuses to exec a file carrying",
        "# capabilities under that flag: the container dies with",
        "# 'exec /usr/bin/caddy: operation not permitted' before it reads a line",
        "# of config, which looks like a broken image and is a run-time flag.",
        f"# Nothing here binds below 1024 — this listens on {port} — so the",
        "# capability buys nothing and removing it is the whole fix.",
        "RUN apk add --no-cache --virtual .setcap libcap \\",
        "    && setcap -r /usr/bin/caddy \\",
        "    && apk del .setcap",
        f"EXPOSE {port}",
        "USER 1000:1000",
        'CMD ["caddy", "run", "--adapter", "caddyfile",'
        ' "--config", "/etc/caddy/Caddyfile"]',
    ]
    return lines, (("Caddyfile", caddyfile),)


def node_static(
    *,
    framework: str,
    reason: str,
    tc: NodeToolchain,
    build_script: str,
    output_dir: str,
    spa: bool,
    port: int = DEFAULT_PORT,
    notes: tuple[str, ...] = (),
) -> BuildPlan:
    """A Node toolchain that produces files, served by Caddy.

    Covers Astro, Vite, Create React App, SvelteKit's static adapter and
    Next.js with `output: 'export'`. The runtime image contains no Node at all.
    """
    lines = _header(framework)
    lines += _install_stage(tc)
    lines += [
        f"FROM {NODE_IMAGE} AS build",
        "WORKDIR /app",
        "COPY --from=deps /app/node_modules ./node_modules",
        "COPY . .",
        "ENV NODE_ENV=production",
        build_env_mount(f"{tc.run_prefix} {build_script}"),
        "",
    ]
    runtime, files = _static_runtime(
        source_stage="build", output_dir=output_dir, spa=spa, port=port
    )
    lines += runtime
    return BuildPlan(
        framework=framework,
        reason=reason,
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
        context_files=files,
    )


def next_standalone(
    *,
    tc: NodeToolchain,
    port: int = DEFAULT_PORT,
    notes: tuple[str, ...] = (),
) -> BuildPlan:
    """Next.js built with `output: 'standalone'`.

    Next traces the modules the server actually reaches and writes a
    self-contained `server.js` beside them, so the runtime stage needs no
    `node_modules` at all. `public/` and `.next/static` are the two things
    tracing deliberately does not include, and forgetting either produces a
    site that renders with no images and no CSS — the single most common way
    to get this wrong.
    """
    lines = _header("Next.js (standalone)")
    lines += _install_stage(tc)
    lines += [
        f"FROM {NODE_IMAGE} AS build",
        "WORKDIR /app",
        "COPY --from=deps /app/node_modules ./node_modules",
        "COPY . .",
        "ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1",
        build_env_mount(f"{tc.run_prefix} build"),
        "# `public` is optional in Next but not optional for the COPY below.",
        "RUN mkdir -p public",
        "",
        f"FROM {NODE_IMAGE} AS run",
        "WORKDIR /app",
        "ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1",
        "# Next's server binds to localhost unless told otherwise, which from",
        "# outside the container looks exactly like a crashed app.",
        f"ENV HOSTNAME=0.0.0.0 PORT={port}",
        "COPY --from=build /app/public ./public",
        "COPY --from=build /app/.next/standalone ./",
        "COPY --from=build /app/.next/static ./.next/static",
        f"EXPOSE {port}",
        "USER node",
        'CMD ["node", "server.js"]',
    ]
    return BuildPlan(
        framework="next-standalone",
        reason="Next.js with output: 'standalone' — serving the traced server bundle",
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
    )


def node_server(
    *,
    framework: str,
    reason: str,
    tc: NodeToolchain,
    build_script: str | None,
    start: str,
    port: int = DEFAULT_PORT,
    prune: bool = True,
    notes: tuple[str, ...] = (),
) -> BuildPlan:
    """A long-running Node process.

    Covers Nuxt, SvelteKit's node adapter, Remix, plain Express and Next.js
    without standalone output. Dev dependencies are pruned after the build
    rather than skipped before it, because most of them — the bundler, the
    TypeScript compiler — are exactly what the build needs.
    """
    lines = _header(framework)
    lines += _install_stage(tc)
    lines += [
        f"FROM {NODE_IMAGE} AS build",
        "WORKDIR /app",
        "COPY --from=deps /app/node_modules ./node_modules",
        "COPY . .",
        "ENV NODE_ENV=production",
    ]
    if build_script:
        lines.append(build_env_mount(f"{tc.run_prefix} {build_script}"))
    if prune:
        prune_cmd = {
            "npm": "npm prune --omit=dev",
            "pnpm": "pnpm prune --prod",
            "yarn": "yarn install --production --ignore-scripts --prefer-offline",
            "bun": "bun install --production",
        }[tc.name]
        lines.append(f"RUN {tc.cache} {prune_cmd} || true")
    lines += [
        "",
        f"FROM {NODE_IMAGE} AS run",
        "WORKDIR /app",
        f"ENV NODE_ENV=production HOST=0.0.0.0 HOSTNAME=0.0.0.0 PORT={port}",
        "COPY --from=build /app ./",
        f"EXPOSE {port}",
        "USER node",
        f"CMD {_exec_form(start)}",
    ]
    return BuildPlan(
        framework=framework,
        reason=reason,
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
    )


def python_server(
    *,
    framework: str,
    reason: str,
    start: str,
    install: str,
    port: int = DEFAULT_PORT,
    notes: tuple[str, ...] = (),
) -> BuildPlan:
    """A Python web application behind uvicorn or gunicorn.

    Dependencies install into a virtualenv that is copied whole into the
    runtime stage, so the image carries the packages without carrying pip's
    cache or any build toolchain that a wheel needed to compile.
    """
    lines = _header(framework)
    lines += [
        f"FROM {PYTHON_IMAGE} AS build",
        "WORKDIR /app",
        # No PIP_NO_CACHE_DIR: the cache is a mount, so it is kept between
        # builds and still never reaches the image. /root/.cache covers pip,
        # uv and poetry alike.
        "ENV PIP_DISABLE_PIP_VERSION_CHECK=1",
        "RUN python -m venv /opt/venv",
        'ENV PATH="/opt/venv/bin:$PATH"',
        "COPY . .",
        f"RUN {cache_mount('/root/.cache', 'python')} {install}",
        "",
        f"FROM {PYTHON_IMAGE} AS run",
        "WORKDIR /app",
        'ENV PATH="/opt/venv/bin:$PATH" PYTHONUNBUFFERED=1',
        f"ENV PORT={port}",
        "COPY --from=build /opt/venv /opt/venv",
        "COPY --from=build /app /app",
        "RUN useradd --uid 10001 --no-create-home --shell /usr/sbin/nologin app",
        "USER 10001",
        f"EXPOSE {port}",
        f"CMD {_exec_form(start)}",
    ]
    return BuildPlan(
        framework=framework,
        reason=reason,
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
    )


def go_server(*, port: int = DEFAULT_PORT, notes: tuple[str, ...] = ()) -> BuildPlan:
    """A Go binary on a distroless base.

    Static linking is forced so the runtime stage can be `base-debian12`, which
    has no shell and no package manager. There is nothing in that image for a
    compromised process to execute.
    """
    lines = _header("Go")
    lines += [
        f"FROM {GO_IMAGE} AS build",
        "WORKDIR /src",
        "COPY go.mod go.su[m] ./",
        f"RUN {cache_mount('/go/pkg/mod', 'go-mod')} go mod download",
        "COPY . .",
        "ENV CGO_ENABLED=0 GOOS=linux",
        build_env_mount(
            "go build -trimpath -ldflags='-s -w' -o /out/server ./...",
            mounts=(
                cache_mount("/go/pkg/mod", "go-mod"),
                cache_mount("/root/.cache/go-build", "go-build"),
            ),
        ),
        "",
        "FROM gcr.io/distroless/base-debian12 AS run",
        "COPY --from=build /out/server /server",
        f"ENV PORT={port}",
        f"EXPOSE {port}",
        "USER 65532:65532",
        'CMD ["/server"]',
    ]
    return BuildPlan(
        framework="go",
        reason="go.mod found — building a static binary on a distroless base",
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
    )


def plain_static(*, port: int = DEFAULT_PORT, notes: tuple[str, ...] = ()) -> BuildPlan:
    """Files that are already the website. No build step at all."""
    lines = _header("static site")
    lines += [
        f"FROM {STATIC_IMAGE} AS source",
        "WORKDIR /app",
        "COPY . ./",
        "",
    ]
    runtime, files = _static_runtime(
        source_stage="source", output_dir=".", spa=False, port=port
    )
    lines += runtime
    return BuildPlan(
        framework="static",
        reason="index.html with no build manifest — serving the directory as-is",
        dockerfile="\n".join(lines) + "\n",
        port=port,
        notes=notes,
        context_files=files,
    )


def _exec_form(command: str) -> str:
    """Render a command as Docker's exec form when it is safe to do so.

    Exec form matters more than it looks: shell form wraps the process in
    `/bin/sh -c`, which does not forward SIGTERM, so every deploy that replaces
    a container waits the full ten seconds for a kill that a correctly-formed
    CMD would have taken instantly. Anything needing shell features keeps the
    shell, explicitly, with `exec` so the signal still arrives.
    """
    if any(ch in command for ch in "|&;<>$*?`"):
        return json.dumps(["/bin/sh", "-c", f"exec {command}"])
    return json.dumps(command.split())
